name: chat_wave
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  faker: ^2.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  bloc: ^8.1.1
  formz: ^0.5.0+1
  connectivity_plus: ^3.0.3
  dio: ^5.0.2
  get_it: ^7.2.0
  floor: ^1.4.1
  sqflite: ^2.2.6
  flutter_animated_dialog: ^2.0.1
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.1
  build_runner: ^2.1.2


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat     
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700