import 'dart:convert';

import 'package:chat_wave/core/data/network/api_error.dart';
import 'package:chat_wave/core/data/network/api_response.dart';
import 'package:chat_wave/core/data/network/b_wave_api.dart';
import 'package:chat_wave/core/data/network/dto/user_info_dto.dart';
import 'package:chat_wave/utils/locator.dart';
import 'package:dio/dio.dart';

class SecretApiClient {
  final _dio = locator<Dio>();

  /// Connected to other user using a secret generated by him
  Future<ApiResponse<UserInfoDto>> connectToFriend(String secret) async {
    final body = jsonEncode(
      {
        'secret': secret,
      },
    );
    final response = await _dio.post(
      '${BWaveApi.baseUrl}connection/connect',
      data: body,
    );
    if (response.statusCode == 200) {
      return ApiResponse(
        isSuccessful: true,
        data: UserInfoDto.fromJson(response.data['connectedUser']),
      );
    } else {
      return ApiResponse(
        isSuccessful: false,
        error: ApiError.fromJson(response.data),
      );
    }
  }
}
